version: "3.9"

services:
  # ----------------------------------------------------
  # 1. Zookeeper (Required for Confluent Kafka)
  # ----------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    networks:
      - internal
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ----------------------------------------------------
  # 2. Kafka Broker
  # ----------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9094" # external access (e.g. local dev tools)
    networks:
      - internal
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ----------------------------------------------------
  # 3. Patient Service
  # ----------------------------------------------------
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    restart: on-failure

    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal

  # ----------------------------------------------------
  # 4. Patient Service DB
  # ----------------------------------------------------
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"
    volumes:
      - patient-management-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ----------------------------------------------------
  # 5. Billing Service
  # ----------------------------------------------------
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    restart: on-failure
    ports:
      - "4001:4001"
      - "9001:9001" # gRPC
    depends_on:
      kafka:
        condition: service_started
    networks:
      - internal

  # ----------------------------------------------------
  # 6. Analytics Service
  # ----------------------------------------------------
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    restart: on-failure
    ports:
      - "4002:4002"
    depends_on:
      kafka:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal

    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005

  auth-service-db:
    image: postgres:15
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"
    volumes:
      #      - patient-management-data:/var/lib/postgresql/data
      - ./db_volumes/auth-service-db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service

    restart: on-failure

#    ports:
#      - "4005:4005"
    environment:
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=x8aRLBjC1V9Tz1IuE3o47gCN88TwOiD4g2KuJX5u6H7EJ5PSpvnM0NYlcbL0W3Dc


    networks:
      - internal
# ----------------------------------------------------
# Networks & Volumes
# ----------------------------------------------------
networks:
  internal:
    driver: bridge

volumes:
  patient-management-data: