###POSTrequest to patient/ Create new patient
POST http://localhost:4004/api/patients
Content-type:application/json

{
  "name": "buh4_TEST KAFKA",
  "email": "testkafkaconsumer6@example.com",
  "address": "penang is KAFKA2",
  "birthDate": "2034-09-04",
  "registerDate":"2025-06-09"
}
###