# =========================
# APPLICATION SETTINGS
# =========================
spring.application.name=patient-service
server.port=4000
logging.level.root=info

# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:postgresql://patient-service-db:5432/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
# Automatically update or create database tables based on entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ensures Hibernate creates schema before data.sql runs
spring.jpa.defer-datasource-initialization=true

# Always run schema.sql and data.sql if they exist
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# =========================
# KAFKA CONFIGURATION
# =========================
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.group-id=patient-service-group
#In memory database
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=none
#
#spring.sql.init.mode=always

